### PR TITLE
Add Responsive Dynamic Form

### LINKED ISSUE #3: Add Contact Us Form
### Feature Description
Currently, the "Contact Us" page shows static contact information, which is not interactive. A contact form would enhance user engagement, allowing visitors to directly reach out with their queries, feedback, or complaints.

### Proposed Solution
Replace the existing contact information with a dynamic form where users can input their name, email address, and message. Upon submission, the form should send an email or store the message in the database for further action.

### Form Fields:

Name (Text Input)
Email (Email Input)
Message (Textarea)
Screenshot 2024-10-05 at 11 48 07 PM

Free to use Bootstrap

### PR DESCRIPTION
**Pull request by chow870**
## Description

Add Responsive Dynamic Form

Fixes #3 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Screenshots (if appropriate):
Already shown to my mentor on discord.

## Checklist:

- [x] I have registered myself at [Contrihub website](https://sac.mnnit.ac.in/contrihub).
- [x] My code follows the code style of this project.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by Codipk — CHANGES_REQUESTED** [review]
@chow870  Add the background same as of about pages 
Screenshot 2024-10-11 at 12 29 42 AM
Also the  space below the form is quite large in 100% view size. Adjust the size of form uniformly in the website

**Comment by chow870** [comment]
sure

**Comment by Codipk** [comment]
Also show the video of sending the msg from contact form .

**Comment by chow870** [comment]
Which message? The confirmation message on clicking the submit button?

**Comment by Codipk** [comment]
yes!

**Pull request closed without merging**
