### PR TITLE
Feature/modify calorie intake calculator

### PR DESCRIPTION
**Pull request by Gprakhar141**
## Description

I have scaled up the Calorie Intake Calculator which now allows the users to enter the meals and the day and get the nutrient composition information accordingly.

## Related Issue

Allows the retrieval of information related to multiple meals at once.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Motivation and Context

This feature is important to provide users with an accurate understanding of their daily calorie intake and nutritional breakdown, allowing them to make informed dietary choices. It will also make the app more personalized and user-friendly.

## How Has This Been Tested?

The project has been set up and tested on the local machine on various inputs of days and meals.

## Screenshots (if appropriate):
Screenshot (52)
Screenshot (51)
PS: Calorie and Protein info not available as it was restricted to premium users on the nutrition-api.

## Checklist:

- [x] I have registered myself at [Contrihub website](https://sac.mnnit.ac.in/contrihub).
- [x] My code follows the code style of this project.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by Codipk** [comment]
@Gprakhar141 Cann't U make item quantity dynamic? User manually enters the item quantity and as per that It will showing the result.

**Comment by Gprakhar141** [comment]
> @Gprakhar141 Cann't U make item quantity dynamic? User manually enters the item quantity and as per that It will showing the result.

@Codipk In what sort, I mean if I select snacks and dinner will I have to give the quantity of each item in snacks and dinner for that day separately???

**Comment by Codipk** [comment]
If u cannot do this then mention in side that it is per 100gm so that user get to know. Ig it would be better to write side of the calculate calorie

**Comment by Gprakhar141** [comment]
Actually doing it would make it frontend as well as backend a lot more cluttery as the user would have to enter each quantity.
It is better to mention the assumption(I have assumed 100g of each food item).

**Comment by Gprakhar141** [comment]
Should I do it???

**Comment by Codipk** [comment]
Yes. Just mention it on frontend

**Comment by Codipk** [comment]
Also make the ui looks better like the alignment of all the things it will give u bonus points

**Comment by Gprakhar141** [comment]
Wait a second I will raise another PR then.

**Pull request closed without merging**
